### PR TITLE
added promise to client.invoke (all cases to check if datasets have been fetched/created)

### PR DESCRIPTION
**Pull request by slugb0t**
updated with no console.logs

### CODE REVIEW

**Comment by slugb0t** [comment]
The PR will add a check on Step 6: of Organizing a dataset. More specifically when a user is trying to create a dataset on a local system. It will check the free memory available on their system and then compare that to the dataset that is trying to be created.
The npm library, 'check-disk-space' was added to simplify the process for getting storage information on OSX, Linux, and Windows.

**Comment by slugb0t** [comment]
Added checks on Prepare Metadata tab to ensure each metadata file being created locally has at least 3MB of storage. Check is done on the final generate button of each metadata file being created. Ensuring that local device will have enough space for the metadata file trying to be created.

**Comment by slugb0t** [comment]
updated some of the code to have event listeners and event-trackers. Modified some variables to let rather than var to keep scope limited to functions.

**Review by aaronm-2112 — COMMENTED** [review]
Does check-disk-space get used?

**Comment by slugb0t** [comment]
> Yeah the library is used in manifest.js and submission.js

**Comment by aaronm-2112** [comment]
Gotcha!

**Pull request merged**
